export const CardOptions = {
  cardTypes: [
    {id: 1, name: '2', type: 'hearts'},
    {id: 2, name: '3', type: 'hearts'},
    {id: 3, name: '4', type: 'hearts'},
    {id: 5, name: '5', type: 'hearts'},
    {id: 6, name: '6', type: 'hearts'},
    {id: 7, name: '7', type: 'hearts'},
    {id: 8, name: '8', type: 'hearts'},
    {id: 9, name: '9', type: 'hearts'},
    {id: 10, name: '10', type: 'hearts'},
    {id: 11, name: 'jack', type: 'hearts'},
    {id: 12, name: 'queen', type: 'hearts'},
    {id: 13, name: 'king', type: 'hearts'},
    {id: 14, name: 'ace', type: 'hearts'},
    {id: 15, name: '2', type: 'tiles'},
    {id: 16, name: '3', type: 'tiles'},
    {id: 17, name: '4', type: 'tiles'},
    {id: 19, name: '5', type: 'tiles'},
    {id: 20, name: '6', type: 'tiles'},
    {id: 21, name: '7', type: 'tiles'},
    {id: 22, name: '8', type: 'tiles'},
    {id: 23, name: '9', type: 'tiles'},
    {id: 24, name: '10', type: 'tiles'},
    {id: 25, name: 'jack', type: 'tiles'},
    {id: 26, name: 'queen', type: 'tiles'},
    {id: 27, name: 'king', type: 'tiles'},
    {id: 28, name: 'ace', type: 'tiles'},
    {id: 29, name: '2', type: 'pikes'},
    {id: 30, name: '3', type: 'pikes'},
    {id: 31, name: '4', type: 'pikes'},
    {id: 33, name: '5', type: 'pikes'},
    {id: 34, name: '6', type: 'pikes'},
    {id: 35, name: '7', type: 'pikes'},
    {id: 36, name: '8', type: 'pikes'},
    {id: 37, name: '9', type: 'pikes'},
    {id: 38, name: '10', type: 'pikes'},
    {id: 39, name: 'jack', type: 'pikes'},
    {id: 40, name: 'queen', type: 'pikes'},
    {id: 41, name: 'king', type: 'pikes'},
    {id: 42, name: 'ace', type: 'pikes'},
    {id: 43, name: '2', type: 'clovers'},
    {id: 44, name: '3', type: 'clovers'},
    {id: 45, name: '4', type: 'clovers'},
    {id: 47, name: '5', type: 'clovers'},
    {id: 48, name: '6', type: 'clovers'},
    {id: 49, name: '7', type: 'clovers'},
    {id: 50, name: '8', type: 'clovers'},
    {id: 51, name: '9', type: 'clovers'},
    {id: 52, name: '10', type: 'clovers'},
    {id: 53, name: 'jack', type: 'clovers'},
    {id: 54, name: 'queen', type: 'clovers'},
    {id: 55, name: 'king', type: 'clovers'},
    {id: 56, name: 'ace', type: 'clovers'}
  ],

  cardRules: [
    {number: '2', rule: 'Choose the one person who have to drink!'},
    {number: '3', rule: 'You are drinking!'},
    {number: '4', rule: 'All the girls drink!'},
    {number: '5', rule: 'Five is tap master!'},
    {number: '6', rule: 'All the guys drink!'},
    {number: '7', rule: 'Seven is heaven!'},
    {number: '8', rule: 'Eight is mate!'},
    {number: '9', rule: 'Nine is rime!'},
    {number: '10', rule: 'Ten is category!'},
    {number: 'jack', rule: 'Choose a rule!'},
    {number: 'queen', rule: 'Question master!'},
    {number: 'king', rule: 'Crown on the head!'},
    {number: 'ace', rule: 'Everyone has to drink!'}
  ]
};


